export const LION = '/images/lion.png'
export const TIGER = '/images/tiger.png'
export const ELEPHANT = '/images/elephant.png'
export const DEER = '/images/deer.png'
export const WOLF = '/images/wolf.png'
export const PANTHER = '/images/panther.png'
export const BAT = '/images/bat.png'
export const BIKE = '/images/bike.jpg'
export const CAR = '/images/car.jpg'
export const BUTTERFLY = '/images/butterfly.jpg'
export const DONKEY = '/images/donkey.png'
export const PARROT = '/images/parrot.png'

export const GAMEOVER = '/images/Background/gameOver.jpg'