export const LION = '/images/lion.jpg'
export const TIGER = '/images/tiger.jpg'
export const ELEPHANT = '/images/elephant.jpg'
export const DEER = '/images/deer.jpg'
export const WOLF = '/images/wolf.jpg'
export const PANTHER = '/images/panther.jpg'